apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-authentication
  namespace: sistal
  labels:
    app: ms-authentication
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-authentication
  template:
    metadata:
      labels:
        app: ms-authentication
    spec:
      containers:
      - name: ms-authentication
        # El pipeline de GitHub Actions actualizará este tag por el Commit SHA real
        image: us-central1-docker.pkg.dev/sistal-490016/sistal-docker-images/ms-authentication:IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Puerto estándar de tu app Go
        
        # AQUÍ CONSUME EL CONFIGMAP MANUAL
        envFrom:
        - configMapRef:
            name: ms-authentication-config
            # optional: true # Descomenta esto si quieres que el pod inicie aunque el configmap no exista
            
        # Buenas prácticas: Límites de recursos
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
